# Generated by Django 4.0.6 on 2023-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de cliente: ')),
                ('patente', models.CharField(max_length=20, verbose_name='Patente: ')),
                ('fechaDeIngreso', models.DateTimeField(auto_now_add=True)),
                ('detalles', models.CharField(max_length=150, verbose_name='Detalles: ')),
                ('total', models.FloatField()),
            ],
        ),
    ]
