# Generated by Django 4.0.6 on 2023-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
