# Generated by Django 5.0.1 on 2024-01-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_clientes_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='age',
            field=models.IntegerField(choices=[(2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031)], verbose_name='Año'),
        ),
    ]
