# Generated by Django 4.0.6 on 2023-09-24 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_clientes_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='detalles',
            field=models.CharField(default=' ', max_length=150, verbose_name='Detalles: '),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fechaDeIngreso',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(default=' ', max_length=50, verbose_name='Nombre de cliente: '),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='patente',
            field=models.CharField(default=' ', max_length=20, verbose_name='Patente: '),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='total',
            field=models.FloatField(blank=True, default=' ', null=True),
        ),
    ]
